const words = [
  "a", "ace", "act", "add", "age", "aim", "air", "ale", "all", "amp",
  "and", "ant", "any", "ape", "app", "apt", "arc", "are", "arm", "art",
  "ash", "ask", "ate", "awe", "axe", "bad", "bag", "ban", "bar", "bat",
  "bay", "bed", "bee", "beg", "bet", "bid", "big", "bin", "bit", "bob",
  "bog", "boo", "box", "boy", "bra", "bud", "bug", "bum", "bun", "bus",
  "but", "buy", "cab", "can", "cap", "car", "cat", "caw", "cod", "cop",
  "cow", "cry", "cub", "cup", "cut", "dab", "dad", "dam", "dan", "day",
  "den", "dew", "did", "dig", "dim", "dip", "dog", "dot", "dry", "dub",
  "dud", "due", "dug", "dye", "ear", "eat", "ebb", "eel", "egg", "ego",
  "elf", "elk", "elm", "end", "era", "eve", "eye", "fab", "fad", "fan",
  "far", "fat", "fax", "fed", "fee", "few", "fig", "fin", "fit", "fix",
  "fly", "fog", "for", "fox", "fun", "fur", "gap", "gas", "gay", "gel",
  "gem", "get", "gig", "gin", "god", "got", "gum", "gun", "gut", "guy",
  "gym", "had", "ham", "has", "hat", "hay", "hem", "hen", "her", "hey",
  "hid", "him", "hip", "hit", "hog", "hop", "hot", "how", "hub", "hug",
  "huh", "hum", "hut", "ice", "icy", "ill", "ink", "inn", "ion", "its",
  "ivy", "jam", "jar", "jaw", "jay", "jet", "jog", "joy", "jug", "jut",
  "ken", "key", "kid", "kin", "kit", "lab", "lad", "lag", "lap", "law",
  "lay", "lea", "led", "leg", "let", "lid", "lie", "lip", "lit", "log",
  "lop", "lot", "low", "mad", "man", "map", "mat", "max", "may", "men",
  "met", "mid", "mix", "mob", "mod", "mom", "moo", "mop", "mot", "mud",
  "mug", "nag", "nap", "net", "new", "nip", "nod", "nor", "not", "now",
  "nun", "oak", "oar", "odd", "off", "oil", "old", "one", "opt", "orb",
  "ore", "our", "out", "owl", "own", "pad", "pal", "pan", "par", "pat",
  "paw", "pay", "pea", "peg", "pen", "pet", "pic", "pie", "pig", "pin",
  "pit", "ply", "pod", "pop", "pot", "pro", "pub", "pup", "put", "rag",
  "ram", "ran", "rap", "rat", "raw", "ray", "red", "rep", "rib", "rid",
  "rig", "rim", "rip", "rob", "rod", "rot", "row", "rub", "rug", "run",
  "sad", "sag", "sap", "sat", "saw", "say", "sea", "see", "set", "sew",
  "she", "shy", "sin", "sip", "sir", "sit", "six", "ski", "sky", "sly",
  "sob", "son", "sow", "soy", "spy", "sub", "sum", "sun", "sup", "tab",
  "tag", "tan", "tap", "tar", "tax", "tea", "ten", "the", "thy", "tie",
  "tin", "tip", "toe", "ton", "top", "tot", "toy", "try", "tub", "tug",
  "two", "urn", "use", "van", "vat", "vet", "vow", "wag", "war", "was",
  "wax", "way", "web", "wet", "who", "why", "wig", "win", "wit", "woe",
  "won", "woo", "wow", "yak", "yam", "yap", "yaw", "yay", "yen", "yes",
  "yet", "yew", "you", "yum", "zap", "zen", "zip", "zoo",
  "absent", "abroad", "accuse", "admire", "advice", "afford", "afraid",
  "agency", "agenda", "almost", "amount", "animal", "annual", "answer",
  "anyone", "appeal", "arrive", "artist", "aspect", "assign", "assist",
  "assume", "attack", "attend", "author", "backed", "barely", "battle",
  "beauty", "became", "become", "before", "behalf", "behave", "behind",
  "belief", "belong", "beneath", "beside", "better", "beyond", "bishop",
  "border", "bottle", "bottom", "bought", "branch", "breath", "bridge",
  "bright", "broken", "budget", "burden", "bureau", "button", "camera",
  "cannot", "carbon", "career", "castle", "casual", "caught", "center",
  "chance", "change", "charge", "choice", "choose", "church", "circle",
  "client", "closed", "closer", "coffee", "column", "combat", "coming",
  "common", "comply", "copper", "corner", "costly", "county", "couple",
  "course", "covers", "create", "credit", "crisis", "custom", "damage",
  "danger", "dealer", "debate", "decade", "decide", "defeat", "defend",
  "define", "degree", "demand", "depend", "deputy", "desire", "detail",
  "detect", "device", "differ", "dinner", "direct", "doctor", "dollar",
  "domain", "donate", "double", "driven", "driver", "during", "easily",
  "eating", "editor", "effect", "effort", "eighth", "either", "elapse",
  "elderly", "eleven", "emerge", "empire", "employ", "enable", "ending",
  "energy", "engage", "engine", "enough", "ensure", "entire", "entity",
  "equity", "escape", "estate", "ethics", "evenly", "exceed", "except",
  "excess", "expand", "expect", "expert", "export", "extend", "extent",
  "fabric", "facing", "factor", "failed", "fairly", "fallen", "family",
  "famous", "father", "fellow", "female", "figure", "filing", "finger",
  "finish", "fiscal", "flight", "flying", "follow", "forced", "forest",
  "forget", "formal", "format", "former", "foster", "fought", "friend",
  "future", "garden", "gather", "gender", "gently", "global", "golden",
  "ground", "growth", "guilty", "handed", "handle", "happen", "hardly",
  "headed", "health", "height", "highly", "honest", "honor", "ignore",
  "impact", "import", "income", "indeed", "injury", "inmate", "inside",
  "intend", "invest", "involve", "island", "itself", "jersey", "joint",
  "journey", "junior", "keeper", "kernel", "killer", "label", "latest",
  "launch", "lawyer", "leader", "league", "legacy", "length", "lesson",
  "letter", "lights", "likely", "limit", "linked", "liquid", "listen",
  "little", "living", "losing", "luxury", "mainly", "manage", "manner",
  "manual", "margin", "market", "master", "matter", "medium", "member",
  "memory", "mental", "merely", "method", "middle", "minute", "mirror",
  "mobile", "modern", "modest", "moment", "money", "monkey", "mostly",
  "mother", "motion", "muscle", "museum", "mutual", "myself", "narrow",
  "nation", "native", "nature", "nearby", "nearly", "nights", "nobody",
  "normal", "notice", "notion", "number", "object", "office", "offset",
  "online", "option", "orange", "origin", "output", "outset", "palace",
  "parent", "partly", "patent", "people", "period", "permit", "person",
  "phrase", "picked", "planet", "player", "please", "plenty", "pocket",
  "police", "policy", "prefer", "pretty", "prince", "prison", "profit",
  "proper", "proven", "public", "pursue", "raised", "random", "rarely",
  "rather", "rating", "reader", "reason", "recall", "recent", "record",
  "reduce", "refuse", "regard", "regime", "region", "relate", "remain",
  "remark", "remind", "remove", "repair", "repeat", "report", "rescue",
  "reside", "resist", "resort", "result", "retail", "retain", "return",
  "reveal", "review", "reward", "ruling", "safety", "saving", "saying",
  "scheme", "school", "screen", "search", "season", "second", "secret"
];


export const CreatePhrase = (length:number = 25) : string[] => {
    
    const dictionaryLength = words.length;
    let arr : string[] = [];
    
    for(let i : number = 0; i < length; i++) {
        const idx = Math.floor(Math.random() * dictionaryLength);
        arr.push(words[idx]);
    }

    return arr;
}